const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const adapter=fs.readFileSync(require.resolve('../scripts/sheet-sales-adapter.js'),'utf8');
const webapp=fs.readFileSync(require.resolve('../scripts/sheet-sales-webapp.gs'),'utf8');
const rows=[['제목'],['판매: 2026.09.10~10.09'],['기준'],[],['상품명','디자이너','공장명','제품 등록일','판매수량','전체 판매비중','신상 내 판매비중','추정 수령 기준\n반품 신청률'],['예시 상품','담당','공장','비공개 날짜',5,'1.0%','50.0%','—','공개하지 않을 사유'],['합계']];
function run(action){const reads=[];const ctx=vm.createContext({console:{error(){}},ContentService:{MimeType:{JSON:'json'},createTextOutput(body){return {body,setMimeType(type){this.type=type;return this;}}}},Sheets:{Spreadsheets:{get(id,options){reads.push({id,options});return {sheets:[{properties:{sheetId:2026100512,title:'🌱 신상_성과'}}]};},Values:{get(id,range,options){reads.push({id,range,options});return {values:rows};}}}}});vm.runInContext(adapter,ctx);vm.runInContext(webapp,ctx);return {response:JSON.parse(ctx.doGet({parameter:{action,sheet:'private',range:'A:Z'}}).body),reads};}
test('fixed read-only endpoint returns six fields and explicit metric, never caller-selected sheets or raw values',()=>{
 const {response,reads}=run('sales');assert.equal(response.ok,true);assert.equal(response.sourceSheetId,2026100512);assert.equal(response.returnMetric.key,'estimated-receipt-return-request-rate');assert.equal(response.items[0].returns,null);assert.deepEqual(Object.keys(response.items[0]).sort(),['designer','factory','name','rank','returns','share']);assert.equal(reads[1].range,"'🌱 신상_성과'!A1:J160");assert.equal(reads[1].options.valueRenderOption,'FORMATTED_VALUE');assert.ok(!JSON.stringify(response).includes('공개하지 않을 사유'));assert.ok(!JSON.stringify(response).includes('비공개 날짜'));
});
test('unsupported actions cannot access the source',()=>{const x=run('write');assert.equal(x.response.ok,false);assert.equal(x.response.error,'unsupported_request');assert.equal(x.reads.length,0);});
