const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('jsdom');
function setup(){const dom=new JSDOM('<div id="host"></div>',{runScripts:'outside-only',url:'https://example.test/'});dom.window.eval(fs.readFileSync(require.resolve('../scripts/sheet-sales-view.js'),'utf8'));return {dom,api:dom.window.AiselSheetSalesView,host:dom.window.document.getElementById('host')};}
const fixture={ok:true,source:'operations-sheet',periodLabel:'2026.09.10~10.09',returnMetric:{key:'estimated-receipt-return-request-rate'},items:[{rank:1,name:'예시 가디건',designer:'담당',factory:'공장',share:1,returns:null},{rank:2,name:'예시 스커트',designer:'담당',factory:'공장',share:20,returns:0}]};
test('actual embedded HTML starts its read-only feed and renders the returned rows',async()=>{
 const path=require('node:path'),root=path.resolve(__dirname,'..');const publicFile=path.join(root,'work-order-5aa994e7.html');const html=fs.readFileSync(fs.existsSync(publicFile)?publicFile:path.join(root,'작업지시서/work-order.html'),'utf8');
 const script=html.match(/<script id="aisel-sheet-sales-view-script">([\s\S]*?)<\/script>/)[1];
 const dom=new JSDOM('<div id="salesAuth"></div><div id="salesSourceNote"></div><input id="salesSearchInput"><select id="salesSort"></select><div><span id="salesPeriod"></span><span id="salesUpdated"></span></div><div id="salesTableBody"></div>',{runScripts:'outside-only'});let calls=0;dom.window.AbortController=AbortController;dom.window.fetch=async()=>{calls++;return {ok:true,json:async()=>({...fixture,readAt:'2026-10-10T10:32:00Z',returnMetric:{key:'sales-cohort-return-request-rate-provisional'}})};};
 dom.window.eval(script);await new Promise(resolve=>setTimeout(resolve,10));assert.equal(calls,1);assert.equal(dom.window.document.querySelectorAll('#salesTableBody .sheet-sales-grid').length,3);assert.equal(dom.window.document.querySelector('.sheet-sales-head').lastChild.textContent,'반품 접수%');assert.equal(dom.window.document.getElementById('sheetSalesRefresh').disabled,false);dom.window.close();
});
test('provisional sales-cohort rate uses its actual meaning in header and full details',()=>{const {dom,api,host}=setup();dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};api.render(host,{...fixture,returnMetric:{key:'sales-cohort-return-request-rate-provisional'}},'');assert.equal(host.querySelector('.sheet-sales-head').lastChild.textContent,'반품 접수%');host.querySelector('button').click();const text=dom.window.document.querySelector('dialog').textContent;assert.match(text,/판매 대비 반품 접수율\(잠정\)/);assert.match(text,/추가 반품으로 바뀔 수/);assert.match(text,/교환은 제외/);dom.window.close();});
test('client keeps unknown and zero distinct, labels current metric and preserves existing ratings/search/details',()=>{const {dom,api,host}=setup();dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};api.render(host,fixture,'');assert.equal(host.querySelector('.sheet-sales-head').lastChild.textContent,'반품 신청%');const rows=host.querySelectorAll('.sheet-sales-grid');assert.equal(rows[1].lastChild.textContent,'—');assert.equal(rows[2].lastChild.textContent,'0.0%');assert.equal(rows[1].querySelector('.sheet-sales-badge').textContent,'저조');assert.equal(rows[2].querySelector('.sheet-sales-badge').textContent,'좋음');rows[1].querySelector('button').click();assert.match(dom.window.document.querySelector('dialog').textContent,/추정 수령 기준 반품 신청률 · —/);assert.match(dom.window.document.querySelector('dialog').textContent,/최종 반품 완료율을 뜻하지 않습니다/);dom.window.AiselWorkorderCodeForName=name=>name.includes('스커트')?'AS-TEST-2':'';api.render(host,fixture,'as-test-2');assert.equal(host.querySelectorAll('.sheet-sales-grid').length,2);assert.equal(host.querySelector('button .sheet-sales-name-label').textContent,'예시 스커트');const before=host.innerHTML;assert.throws(()=>api.render(host,{...fixture,returnMetric:{key:'unverified'}},''));assert.equal(host.innerHTML,before);api.render(host,{...fixture,returnMetric:undefined},'');assert.equal(host.querySelector('.sheet-sales-head').lastChild.textContent,'반품%');dom.window.close();});
test('read-only client never converts failed feed to zero or silently accepts unknown metric',async()=>{const {dom,api}=setup();const calls=[];dom.window.AbortController=AbortController;dom.window.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>fixture};};const endpoint='https://script.google.com/macros/s/fixture/exec';assert.equal((await api.read(endpoint)).items.length,2);assert.equal(calls[0].options.credentials,'omit');assert.equal(calls[0].options.cache,'no-store');assert.equal(calls[0].url,endpoint+'?action=sales');dom.window.fetch=async()=>({ok:true,json:async()=>({ok:false,error:'source_unavailable'})});await assert.rejects(api.read(endpoint));dom.window.fetch=async()=>({ok:true,json:async()=>({...fixture,returnMetric:{key:'unknown'}})});await assert.rejects(api.read(endpoint));dom.window.close();});
